# Generated by Django 5.2.3 on 2025-12-07 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_landingpage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('key_feature', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.ImageField(upload_to='Vertical-image')),
                ('order', models.IntegerField(default=0, help_text='Image order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
