# Generated by Django 5.2.3 on 2025-12-08 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_herosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='image_url',
        ),
        migrations.CreateModel(
            name='HeroSectionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.ImageField(upload_to='hero-gallery')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='homepage.herosection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
