# Generated by Django 5.2.3 on 2025-12-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_herosection_image_url_herosectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosectionimage',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.herosection'),
        ),
    ]
