# Generated by Django 5.2.3 on 2025-12-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
        migrations.DeleteModel(
            name='PopularProduct',
        ),
    ]
