# Generated by Django 5.2.3 on 2025-12-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_featured_product_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feature',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
