# Generated by Django 5.2.3 on 2025-12-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_shopcategorygroup_shopcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
