# Generated by Django 5.2.3 on 2025-12-09 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_shopcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('image_url', models.ImageField(upload_to='occasion')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='group',
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_categories', to='products.occasion'),
        ),
        migrations.DeleteModel(
            name='ShopCategoryGroup',
        ),
    ]
