# Generated by Django 5.2.3 on 2025-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_occasion_remove_shopcategory_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occasion',
            name='image_url',
        ),
        migrations.AddField(
            model_name='occasion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='occasion/'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.occasion'),
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
