# Generated by Django 5.2.3 on 2025-12-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_occasion_image_url_occasion_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occasion',
            old_name='image',
            new_name='image_url',
        ),
    ]
