# Generated by Django 5.2.3 on 2025-12-22 16:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_image_occasion_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Mother, Wife, Father, Brother', max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('neutral', 'Gender Neutral')], default='neutral', max_length=10)),
                ('tagline', models.CharField(help_text="e.g., 'For the one who means everything', 'Your life partner'", max_length=255)),
                ('image', models.ImageField(help_text='Recipient category image', upload_to='recipients/')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this recipient on the website')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Occasion', 'verbose_name_plural': 'Occasions'},
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='image_url',
        ),
        migrations.AddField(
            model_name='occasion',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Occasion banner image', upload_to='occasions/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occasion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/hide this occasion on the website'),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(blank=True, help_text='Which occasions is this product suitable for?', related_name='products', to='products.occasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Who is this product for? (Mother, Father, etc.)', related_name='products', to='products.recipient'),
        ),
    ]
