# Generated by Django 5.2.3 on 2025-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_recipient_alter_occasion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='3D model file (.glb, .gltf format recommended)', null=True, upload_to='products/3d_models/'),
        ),
    ]
