# Generated by Django 5.2.3 on 2025-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='List of color objects: [{"name": "Terracotta", "hex": "#E2725B"}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='List of materials: ["Ceramic", "Wood", "Metal"]'),
        ),
    ]
