# Generated by Django 5.2.3 on 2025-12-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='category',
            new_name='team',
        ),
    ]
