# Generated by Django 5.2.3 on 2025-12-30 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_heroimage_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Journey Milestone',
                'verbose_name_plural': 'Journey Milestones',
                'ordering': ['order'],
            },
        ),
    ]
