# Generated by Django 5.2.3 on 2025-12-09 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('busines_hour', models.CharField(max_length=255)),
                ('tiktok', models.URLField(blank=True, max_length=255)),
                ('whatsapp', models.URLField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
