# Generated by Django 5.2.3 on 2025-12-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetail',
            new_name='Company_info',
        ),
    ]
