# Generated by Django 5.2.3 on 2025-12-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_contactdetail_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='taglines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
