# Generated by Django 5.2.3 on 2025-12-09 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_company_info_taglines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_info',
            name='taglines',
        ),
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taglines', to='contact.company_info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
