# Generated by Django 5.2.3 on 2025-12-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_company_info_taglines_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_info',
            old_name='busines_hour',
            new_name='business_hour',
        ),
    ]
